---
title: "erasmus"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{erasmus}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(hellohaplo)
```


```{r eval=FALSE, include=FALSE}

# Load the key
key <- Sys.getenv("HAPLO_API_KEY")

# Get RSM faculty refs
RSM_FACULTY_REF <- "801yv"
rsm_faculty_refs_vector <- get_people_by_faculty(RSM_FACULTY_REF, key = key)

# Get ESE faculty refs
ESE_FACULTY_REF <- "801y5"
ese_faculty_refs_vector <- get_people_by_faculty(ESE_FACULTY_REF, key = key)

# Get all ethics applications Refs
ETHICS_APPLICATIONS_REF <- "801w6"
all_ethics_refs <- get_linked_objects(ETHICS_APPLICATIONS_REF, key = key)

# Create a df for all applications
ethics_applications <- tibble(
  app_ref = all_ethics_refs
)

## Query all applications ** Takes a long time!!! **
start_time <- Sys.time()
ethics_applications <- ethics_applications |>
  sample_n(10) |>
  mutate(res = map(
    app_ref,
    get_object_info
  ))
end_time <- Sys.time()
print(end_time - start_time)


# Post-processing
# Get the content
ethics_applications <- ethics_applications |>
  mutate(content = map(
    res,
    pluck_content
  ))

# Pluck applicants
ethics_applications <- ethics_applications |>
  mutate(applicants = map(
    content,
    pluck_applicant
  ))


## Get the first applicant for each application
ethics_applications <- ethics_applications |>
  mutate(first_applicant = map_chr(
    applicants,
    ~ .[1]
  ))


# Create a column to label faculty
ethics_applications <- ethics_applications |>
  mutate(
    faculty = case_when(
      first_applicant %in% rsm_faculty_refs_vector ~ "RSM",
      first_applicant %in% ese_faculty_refs_vector ~ "ESE"
    )
  )

```